### ISSUE TITLE
login failed

### ISSUE THREAD

**Issue by danyaegoist** [stormpath/loopback-stormpath#1]
Without dependency "base" : "User"(Persisted in code) there are no login,logout and others methods(I see it in explorer). With User base work "logout" and "registration", but login didnt work.
What I have to do to fix the login? 
on login i have resp - "login failed" even if credentials are correct

**Comment by rdegges** [comment]
Hey there!

You're completely right -- I'm going to get this resolved. Originally I did it this way as the base 'User' model contains a bunch of hashing stuff that doesn't apply to our integration -- and it was causing issues. Going forward, however, I think it's best to base it on the user model and remove things that aren't necessary.

**Comment by rdegges** [comment]
I'll update this ticket as progress is made =)

**Comment by danyaegoist** [comment]
I hope in future we start using a stormpath

2015-05-18 19:52 GMT+03:00, Randall Degges <notifications@github.com>:

**Comment by rdegges** [comment]
Awesome! Me too ^^

**Comment by rdegges** [comment]
Quick update: working on this now.

**Comment by rdegges** [comment]
So, after taking a more in-depth look at this -- I think the best approach is to leave this as a subclass of the base model -- not User.

The reason is this: the User model itself contains a lot of stormpath-incompatible code. What I'm doing instead is copying the relevant bits into the StormpathUser implementation which will allow us to provide this functionality in a simpler manner.

Going to close this ticket.

NOTE: I'm actively working on implementing the User methods =)
